node questgen.js questions_example1.txt
node questgen.js questions_example2.txt
node questgen.js questions_example3.txt
node questgen.js questions_example4.txt
node questgen.js questions_example5.txt
node questgen.js questions_example6.txt
node questgen.js questions_example7.txt
node questgen.js questions_example8.txt
node questgen.js questions_example9.txt
node questgen.js questions_examplea.txt
node questgen.js questions_exampleb.txt